// <auto-generated />
namespace report.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PE));
        
        string IMigrationMetadata.Id
        {
            get { return "201903031431119_PE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
